### ISSUE TITLE
Missing functionality checklist & discussion

### ISSUE THREAD

**Issue by k06a** [near/near-api-js#128]
Nearlib expected to be used by DApps and DWallets and it functionality should cover:

- [ ] Blockchain structure:
  - [x] Block header by (`block.number` or `block.hash`)
  - [x] Shard header by (`block` and `shard.index`) or `shard.hash`
  - [x] Transaction header by (`shard` and `transaction.index`) or `transaction.hash` or `account.nonce` or `address.nonce`
  - [x] Transaction header by (`shard` and `transaction.index`) or `transaction.hash`
  - [x] Latest block number
  - [x] Main coin balance
  - [x] Merkle proofs of different structures
- [ ] Account management:
  - [ ] Transaction internal and external (hardware wallets) signing
  - [ ] Custom message signing similar to EIP-712
- [ ] Smart contract interaction:
  - [x] Calling view methods of smart contract without on-chain tx
  - [ ] Creating transactions by forming method call arguments

**Comment by nearmax** [comment]
Assigning to @frol to provide info on which of this stuff is currently available through RPC, as requested by @vgrichina  in https://docs.google.com/document/d/1smsGXpZEWkoSbLb0dOMwCWfKYmClERq7bqEFLC-X0NE/edit

**Comment by frol** [comment]
Hmm, either I don't understand something, or most of the "blockchain structure" items are, in fact, implemented.

- [x] Block header by (`block.number` or `block.hash`): https://github.com/nearprotocol/nearlib/blob/2987fdbfe790e6a07214dc5fc2937cf4d9a9bce4/src.ts/providers/json-rpc-provider.ts#L61-L63
- [x] Shard header by (`block` and `shard.index`) or `shard.hash`: https://github.com/nearprotocol/nearlib/blob/2987fdbfe790e6a07214dc5fc2937cf4d9a9bce4/src.ts/providers/json-rpc-provider.ts#L65-L67
- [x] Transaction header by (`shard` and `transaction.index`) or `transaction.hash`: https://github.com/nearprotocol/nearlib/blob/2987fdbfe790e6a07214dc5fc2937cf4d9a9bce4/src.ts/providers/json-rpc-provider.ts#L49-L51 (Though, I don't understand what `transaction.index` is. You can only query by transaction hash)
- [x] Latest block number: https://github.com/nearprotocol/nearlib/blob/2987fdbfe790e6a07214dc5fc2937cf4d9a9bce4/src.ts/providers/json-rpc-provider.ts#L40-L42

I need some clarification on the following items:

* Main coin balance -- what is that?
* Merkle proofs of different structures -- which structures? `chunk` RPC exposes `encoded_merkle_root`. Is this what is needed?

**Comment by k06a** [comment]
@frol very nice!

>(Though, I don't understand what transaction.index is. You can only query by transaction hash)

I mean if anyone with to enumerate:
- All Txs in chunk
- All chunks in block

>Main coin balance -- what is that?

"Main coin balance" is NEAR balance, since NEAR is the main coin on the platform.

>Merkle proofs of different structures -- which structures? chunk RPC exposes encoded_merkle_root. Is this what is needed?

It would be really useful to have Merkle proofs for:
- Tx in chunk
- Chunk in Block

I also forgot about TxResults with Merkle roots.

**Comment by frol** [comment]
> I mean if anyone wish to enumerate

Well, it makes perfect sense in the future once we have lots of transactions in a single chunk. I am keeping this in mind when I design the new API (WAMP-proto based) in a background. The current RPC does not have this.

> "Main coin balance"

Is it fine to be exposed via the `status` RPC? /cc @nearmax I need to learn where this information is available inside nearcore.

> It would be really useful to have Merkle proofs for: Chunk in block

The `block` RPC and `chunk` RPC provide `encoded_merkle_root` of a chunk. Is this what is needed?

> It would be really useful to have Merkle proofs for: Tx in chunk
> It would be really useful to have Merkle proofs for: TxResults

I don't see this information exposed via RPC. Please, create a tracking issue (please, include the motivation and whether it is blocking you).

**Comment by bowenwang1996** [comment]
@frol @k06a  account balance can be queried through `query` rpc. Merkle root of tx results is included in the chunk header.

**Comment by frol** [comment]
@bowenwang1996 Which account should one query to get the "main coin balance"?

**Comment by bowenwang1996** [comment]
Actually I am slightly confused here. Does "main coin balance" mean total supply or something account specific?

**Comment by k06a** [comment]
@bowenwang1996 "coins" are native blockchain assets, "tokens" are smart contract based assets.

**Comment by bowenwang1996** [comment]
@k06a I understand. I am asking whether you are talking about account balance or total supply.

**Comment by k06a** [comment]
@bowenwang1996 account balance

**Comment by bowenwang1996** [comment]
I see. For that you can use query rpc and pass `account/<account_id>` to get the account view, which contains balance.

**Comment by nearmax** [comment]
@frol It seems like we have figured out that @k06a was asking for the thing we already have, no need to add it.

**Comment by vgrichina** [comment]
@k06a is there anything still missing apart from interface for external wallet signing?

**Comment by nearmax** [comment]
@k06a ping.

**Comment by k06a** [comment]
@vgrichina will check when will work on EthRelay

**Comment by janedegtiareva** [comment]
Ping from a bugscrub: is this issue still relevant? @k06a

**Comment by k06a** [comment]
@janedegtiareva not really, most of the features are already implemented
